### ISSUE TITLE
Add --detach option for the `up` command to launch processes in the background

### ISSUE THREAD

**Issue by jgoux** [F1bonacc1/process-compose#169]
Hello 👋,

## Feature Request

I'd like to be able to launch `process-compose up` in the background, without any logs being printed to the current terminal.

#### Use Case:

I'm interested in this feature in the context of CI. I'm using [devenv](https://devenv.sh/) to bootstrap my infrastructure, and devenv now relies on process-compose to handle multiple services (for example PostgreSQL).

I read that sending processes in the background was doable since v1.0.0 but it needs to be done within the terminal UI. In my case I don't want to interact with the terminal UI at all.

#### Proposed Change:

Add a `--detach` / `-d` option to `process-compose up` to send it to the background.

It would be similar to docker-compose up --detach: https://docs.docker.com/reference/cli/docker/compose/up/

#### Who Benefits From The Change(s)?

I guess everyone who launches process-compose in a non-interactive environment?

**Comment by VanCoding** [comment]
What would be needed for this? Here's what I guess should happen when the "--detach" option is set:
- ensure that the httpServer is enabled, fail otherwise
- start another, detached process with the same args, without the TUI
- exit with code 0 (but let the detached process continue to run)

But I think that doesn't make much sense, if there's no option to tell the "parent" process to wait until a specified list of processes become healthy. Therefore I suggest to also add an option "--wait-until-healthy [process-name]", which can be provided multiple times for every process that should be healthy before exiting.

Then, if the detached process exits before these processes become healthy, the parent-process errors and exits with a non-zero code. Otherhise, if all the processes become healthy, the parent process exits with code 0.

**Comment by KDanisme** [comment]
In my case I settled with launching process-compose in the background with the http server and waiting until a conditan is met.
```
wait-until process-compose process list --port 5000 -o json | jq '.[] |= .is_ready == \"Ready\" or .status == \"Completed\" | all'"
``` 
This handles cases where there are long running and dependent processes alike which i need to wait for.

`wait-until` is a simple bash script which runs the command until it succeeds, with a timeout

**Comment by F1bonacc1** [comment]
Thank you for your patience! 🙏🏻 
Added in v1.24.0

**Comment by VanCoding** [comment]
@F1bonacc1 Thanks! :) I'll try to integrate it into https://github.com/Platonic-Systems/process-compose-flake

**Comment by adamcstephens** [comment]
This is in fact [now added](https://github.com/Platonic-Systems/process-compose-flake/pull/87) to process-compose-flake.
