### ISSUE TITLE
Add option to show started/starting processes by default

### ISSUE THREAD

**Issue by stijnveenman** [F1bonacc1/process-compose#207]
## Feature Request
The feature of being able to see all processes, even those disabled is great. However, this leads to me basically **always** pressing Ctrl-D on startup. And only sometimes using it to start another process. It would be great to have a way to only show enabled by default
 
#### Proposed Change:
For me personally, i think defaulting to only showing enabled by default makes sense. However, this does change behaviour. So either adding an env var and startup argument (env var is my preferred method, so i don't have to always type the argument) would be sufficient as well.  

#### Who Benefits From The Change(s)?
Anyone with a large number of processes that often only starts a small subset of processes.

**Comment by F1bonacc1** [comment]
Hi @stijnveenman,

That's a good proposal.
Today PC already has the `--hide-disabled` flag. Unfortunately, it was added before the ability to hide (as opposed to remove) the disabled processes.
What I am thinking is to convert it to a "hide" instead of "remove" behavior. I believe that from a user perspective, it will look the same, and add the ability to "unhide" them with `Ctrl-D`.

What do you think?

**Comment by stijnveenman** [comment]
I think that makes sense, also from a UX perspective it makes more sense with the introduction of the new feature. 
Does this have an environment variable linked to it?

**Comment by F1bonacc1** [comment]
> Does this have an environment variable linked to it?

No, but I will add it (actually already did)

**Comment by F1bonacc1** [comment]
Added in v1.18.0

Cheers ✌🏻
