### ISSUE TITLE
Allow clicking on shortcut buttons at the bottom of the screen

### ISSUE THREAD

**Issue by bouk** [F1bonacc1/process-compose#252]
#### Use Case:

I'd like to be able to exit process-compose by clicking 'Quit' at the bottom of the screen

#### Proposed Change:

Change the shortcut labels to buttons you can click

#### Who Benefits From The Change(s)?

Users who don't know how to about F10/ctrl-c

**Comment by F1bonacc1** [comment]
Hi @bouk,

What do you think of a command palette mode as an alternative?
![command](https://github.com/user-attachments/assets/153e1ac2-99e6-46f0-b679-57a6b9049853)
Select with arrows or (j,k for VIM users) and activate with Enter.

P.S.
In this sample (although it doesn't look like it because of the FPS) the Quit action was selected and pressed Enter.

**Comment by calops** [comment]
I think the command palette is cool but not really an alternative to this. I agree that clicking would be nice. If the buttons are there, always-present on the screen, then it wouldn't hurt to make them clickable.

**Comment by F1bonacc1** [comment]
Added in v1.40.0
